FROM python:3.10-slim

WORKDIR /app

# Install dependencies
COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy backend code
COPY backend/ /app/backend/

# Copy ml data folders if any
COPY datasets/ /app/datasets/
COPY models/ /app/models/
COPY scripts/ /app/scripts/

# Default port for FastAPI
EXPOSE 8000

ENV PYTHONPATH=/app/backend

CMD ["uvicorn", "backend.app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
